### ISSUE TITLE
Inference. got error

### ISSUE THREAD

**Issue by MonolithFoundation** [egorsmkv/marblenet-inference#2]
TypeError: Output shape mismatch occured for audio_signal in module AudioToMultiLabelDataset : 
Output shape expected = (batch, time) | 
Output shape found : torch.Size([1, 3129917, 2])

Hi, any help for this

**Comment by egorsmkv** [comment]
show the code

**Comment by egorsmkv** [comment]
maybe your audio file is stereo, convert it to mono

**Comment by MonolithFoundation** [comment]
@egorsmkv exactly：

Input File     : '../data/audios/extracted_audio_clean.wav'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:03:15.62 = 8626831 samples = 14671.5 CDDA sectors
File Size      : 34.5M
Bit Rate       : 1.41M
Sample Encoding: 16-bit Signed Integer PCM

will try it again
